FROM bitnami/spark:latest
USER root
RUN install_packages curl

RUN apt-get update 
# Download the Azure Storage SDK for Java library
RUN curl -L https://download.microsoft.com/download/3/A/3/3A39D257-C06F-467A-9C19-622E8D8640BD/azure-storage-java-9.8.1.jar -o /opt/bitnami/spark/jars/azure-storage-java-9.8.1.jar
RUN curl -L https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-azure/3.3.6/hadoop-azure-3.3.6.jar -o /opt/bitnami/spark/jars/hadoop-azure-3.3.6.jar
RUN curl -L https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-common/3.3.3/hadoop-common-3.3.3.jar 

USER 1001
