version: '3'

x-spark-common: &spark-common
  build:
    context: .
    dockerfile: Dockerfile.spark
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
  networks:
    - spark-flow-network
  environment:
    HADOOP_OPTIONAL_TOOLS: hadoop-azure


x-spark-common-worker: &spark-common-worker
  <<: *spark-common
  command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  depends_on:
    - spark-master
  environment:
    SPARK_MODE: worker
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 1g
    SPARK_MASTER_URL: spark://spark-master:7077
    

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - airflow.env
  volumes:
    - ./jobs:/opt/airflow/jobs
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
  depends_on:
    - postgres
  networks:
    - spark-flow-network

services:
  spark-master:
    <<: *spark-common
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"

  spark-worker-1:
    <<: *spark-common-worker

  spark-worker-2:
    <<: *spark-common-worker
    

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - spark-flow-network

  webserver:
    <<: *airflow-common
    user: "0:0"  # UID:GID of the 'airflow' user, adjust if needed
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - scheduler

  scheduler:
    <<: *airflow-common
    user: "0:0"  # UID:GID of the 'airflow' user, adjust if needed
    command: bash -c "airflow db migrate && airflow users create --username admin --firstname Emmanuel --lastname Adepoju --role Admin --email femiemmanuel1990@gmail.com --password admin && airflow scheduler"

networks:
  spark-flow-network: